### PR TITLE
fix #90 Eliminate isEmpty in shutdown fixes NPE

### LINKED ISSUE #90: NullPointerException race condition when shutting down fifo pool
## Expected Behavior
Shutting down the pool should finish successfully.

## Actual Behavior
Occasionally a NPE is thrown while failing FIFO pending borrowers.

## Steps to Reproduce

```java
@ParameterizedTest
@MethodSource("allPools")
void raceShutdownAndAcquireInvalidate(Function<PoolBuilder<AtomicInteger, ?>, AbstractPool<AtomicInteger>> configAdjuster) {
	AtomicInteger ai = new AtomicInteger();
	PoolBuilder<AtomicInteger, PoolConfig<AtomicInteger>> configBuilder = PoolBuilder
			.from(Mono.fromSupplier(() -> {
				ai.incrementAndGet();
				return ai;
			}))
			.evictionIdle(Duration.ZERO)
			.destroyHandler(resource -> Mono.fromRunnable(resource::decrementAndGet))
			.sizeBetween(0, 1);

	AtomicReference<Throwable> errorRef = new AtomicReference<>();
	for (int i = 0; i < 100_000; i++) {
		errorRef.set(null);
		InstrumentedPool<AtomicInteger> pool = configAdjuster.apply(configBuilder);

		if (i % 2 == 0) {
			RaceTestUtils.race(
					() -> pool.disposeLater().subscribe(v -> {}, errorRef::set),
					() -> pool.acquire()
					          .flatMap(PooledRef::invalidate)
					          .onErrorResume(PoolShutdownException.class, e -> Mono.empty())
					          .subscribe(v -> {}, errorRef::set)
			);
		}
		else {
			RaceTestUtils.race(
					() -> pool.acquire()
					          .flatMap(PooledRef::invalidate)
					          .onErrorResume(PoolShutdownException.class, e -> Mono.empty())
					          .subscribe(v -> {}, errorRef::set),
					() -> pool.disposeLater().subscribe(v -> {}, errorRef::set)
			);
		}
		if (errorRef.get() != null) {
			errorRef.get().printStackTrace();
		}
		assertThat(errorRef.get()).as("exception in " + configAdjuster.toString() + " iteration " + i).isNull();
	}
	assertThat(ai).as("creates and destroys stabilizes to 0").hasValue(0);
}
```

```
[exception in simplePool FIFO iteration 16313] 
Expecting:
 <java.lang.NullPointerException>
to be equal to:
 <null>
but was not.
```

## Possible Solution
The `PENDING` queue can occasionally produce a `null` on `poll()` despite `isEmpty()` returning `false`:
```java
                while(!q.isEmpty()) {
                    q.poll().fail(new PoolShutdownException());
                }
```
Instead of double reading, one can simply just `poll()` and check for nulls:

```java
                Borrower<POOLABLE> nextPending;
                while((nextPending = q.poll()) != null) {
                    nextPending.fail(new PoolShutdownException());
                }
```

### PR DESCRIPTION
**Pull request by simonbasle**
to be merged-with-rebase

### CODE REVIEW

File: src/test/java/reactor/pool/CommonPoolTest.java [hunk 1]
```diff
@@ -2167,4 +2163,134 @@ void poolCloseRacingWithRelease(Function<PoolBuilder<AtomicInteger, ?>, Abstract
...
+				.from(Mono.fromSupplier(() -> {
+					ai.incrementAndGet();
+					return ai;
+				}))
+				.evictionIdle(Duration.ZERO)
+				.destroyHandler(resource -> Mono.fromRunnable(resource::decrementAndGet))
+				.sizeBetween(0, 1);
+
+		AtomicReference<Throwable> errorRef = new AtomicReference<>();
+		for (int i = 0; i < 100_000; i++) {
```
Comment (bsideup) [inline src/test/java/reactor/pool/CommonPoolTest.java:2180]: Just an idea: looks like a good use case for JCStress :)

Comment (simonbasle) [reply src/test/java/reactor/pool/CommonPoolTest.java:2180]: yeah I know, I'll need to convert these to JCStress at one point
