### PR TITLE
fix #98 Don't fail too fast to acquire if maxPending is reached

### LINKED ISSUE #98: Acquire always fails when about to reach maxPending, even if pool has idle resource / allocation capacity
## Expected Behavior
Setting `maxPending` to `n` fails the n-th `acquire` only if there is no idle resource AND no capacity in the pool for allocating a new resource.

Setting `maxPending(0)` would fail without ever "parking" an `acquire`, but `acquire` should be possible if the pool has idle resources or capacity to allocate.

## Actual Behavior
Setting `maxPending(0)` turns every `acquire` into a failure, even if there is an idle resource, or some capacity to allocate.

Similarly, setting it higher results in an off-by one error where the pool should allow an allocation to take place.

## Steps to Reproduce
```java
	@ParameterizedTest
	@MethodSource("allPools")
	void maxPendingZero(Function<PoolBuilder<Integer, ?>, AbstractPool<Integer>> configAdjuster) {
		AtomicInteger source = new AtomicInteger();
		PoolBuilder<Integer, PoolConfig<Integer>> configBuilder = PoolBuilder
				.from(Mono.fromSupplier(source::incrementAndGet))
				.sizeBetween(1, 2)
				.maxPendingAcquire(0);

		AbstractPool<Integer> pool = configAdjuster.apply(configBuilder);

		assertThat(pool.warmup().block(Duration.ofSeconds(1))).as("warmup").isOne();

		//there is one idle resource
		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
				.as("acquire on idle")
				.isNotNull()
				.hasFieldOrPropertyWithValue("poolable", 1);

		//there is now idle resource, but still capacity
		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
				.as("acquire on allocate")
				.isNotNull()
				.hasFieldOrPropertyWithValue("poolable", 2);

		//there is now idle resource, but still capacity
		assertThatExceptionOfType(PoolAcquirePendingLimitException.class)
				.isThrownBy(() -> pool.acquire().block(Duration.ofSeconds(1)))
				.as("acquire on maxPending")
				.withMessage("No pending allowed and pool has reached allocation limit");
	}

	@ParameterizedTest
	@MethodSource("allPools")
	void maxPendingOne(Function<PoolBuilder<Integer, ?>, AbstractPool<Integer>> configAdjuster)
			throws InterruptedException {
		AtomicInteger source = new AtomicInteger();
		PoolBuilder<Integer, PoolConfig<Integer>> configBuilder = PoolBuilder
				.from(Mono.fromSupplier(source::incrementAndGet))
				.sizeBetween(1, 2)
				.maxPendingAcquire(1);

		AbstractPool<Integer> pool = configAdjuster.apply(configBuilder);

		assertThat(pool.warmup().block(Duration.ofSeconds(1))).as("warmup").isOne();

		//there is one idle resource
		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
				.as("acquire on idle")
				.isNotNull()
				.hasFieldOrPropertyWithValue("poolable", 1);

		//there is now idle resource, but still capacity
		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
				.as("acquire on allocate")
				.isNotNull()
				.hasFieldOrPropertyWithValue("poolable", 2);

		//there is now idle resource, no capacity, but pending 1 is allowed
		//in order to test the scenario where we've reached maxPending, this pending must not be cancelled
		final CountDownLatch latch = new CountDownLatch(1);
		final AtomicReference<Throwable> endingSignal = new AtomicReference<>();
		pool.acquire().timeout(Duration.ofSeconds(1))
		    .doFinally(s -> {
		    	latch.countDown();
		    })
		    .subscribe(v -> {}, endingSignal::set);

		//there is now idle resource, no capacity and we've reached maxPending
		assertThatExceptionOfType(PoolAcquirePendingLimitException.class)
				.isThrownBy(() -> pool.acquire().block(Duration.ofSeconds(1)))
				.as("pending acquire on maxPending")
				.withMessage("Pending acquire queue has reached its maximum size of 1");

		//post-assert the intermediate
		assertThat(latch.await(2, TimeUnit.SECONDS)).as("pending 1 was parked for 1s").isTrue();
		assertThat(endingSignal.get()).as("pending 1 timed out after 1s").hasMessageStartingWith("Did not observe any item or terminal signal within 1000ms");
	}
```

## Possible Solution
Check the `idleResource` size and `allocationStrategy` in `SimpleDequePool#pendingOffer`.

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
+/*
+ * Copyright (c) 2018-Present Pivotal Software Inc, All Rights Reserved.
```
Comment (bsideup) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:2]: nit: VMware

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+	@JCStressTest
+	@Outcome(id = {"ACQUIRED 1, 0"}, expect = ACCEPTABLE,  desc = "acquired")
+	@Outcome(id = {"NOT ACQUIRED, 1"}, expect = ACCEPTABLE,  desc = "acquired failed fast during/before destroy")
+	@Outcome(id = {"ACQUIRED 111, 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
+	@Outcome(id = {"ACQUIRED 1111, 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
+	@State
+	public static class MaxPendingAcquireWhileDestroying {
+
+		final AtomicInteger resource = new AtomicInteger(111);
```
Comment (bsideup) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:56]: is it possible to avoid "magical numbers"? Took me a bit of time to figure out that `ACQUIRED 111` & `ACQUIRED 1111` are different (I guess I have some sort of "repeated numbers blindness" :D

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+		final AtomicBoolean firstResourceCreated = new AtomicBoolean();
+
+		final SimpleDequePool<AtomicInteger> pool = PoolBuilder
+				.from(Mono.defer(() -> {
+					if (firstResourceCreated.getAndSet(true)) {
+						return Mono.just(new AtomicInteger(1));
```
Comment (bsideup) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:62]: is it me, or it feels like two tests in one, and that we should rather extract a set of stress tests for `firstResourceCreated`-like scenarios, to not pollute the `MaxPendingAcquireWhileDestroying` ones?

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+				.evictionPredicate((res, meta) -> {
+					int v = res.get();
+					return v > 0 && v != 111;
+				})
+				.destroyHandler(ai -> Mono.fromRunnable(() -> ai.addAndGet(1000)))
+				.build(conf -> new SimpleDequePool<>(conf, true));
+
+		private final PooledRef<AtomicInteger> ref;
+
+		{
```
Comment (bsideup) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:79]: does it really need to be an instance initializer? Doesn't seem to throw, so the field initializer can be used

Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:68]: indeed, leftover from a previous iteration

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 3 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java]: I don't think so. The `firstResourceCreated` is there to ensure we produce a (wildly) different `AtomicInteger`, which happens once the first one has been evicted. Having a big difference in the value allows to easily test which one the `acquisition` method saw.

that said I think the test can now be slightly simplified by not requiring the `resource` itself to be a field.

Comment (bsideup) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:53]: Yet it doesn't feel like the creation of resources should be tested in `MaxPendingAcquireWhileDestroying`

Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:52]: we don't test it per se, but it is part of the state in which we want our test to occur. reaching `maxPending` is not supposed to be possible if the `acquire` can be served by an available resource. we compete between resource A's eviction and resource B's allocation for the purpose of `acquire`, and test that said `acquire` 1) doesn't fail with a `maxPending` and 2) does indeed trigger an allocation

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 1 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:2]: the license plugin should either be removed or all the license headers should be updated. will be done another time in either way

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 3 above)
Comment (bsideup) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:52]: Ok, I think now I understand it better, thanks!

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+	@Outcome(id = {"ACQUIRED '1', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
+	@Outcome(id = {"ACQUIRED '1234', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
+	@State
+	public static class MaxPendingAcquireWhileDestroying {
+
+		final AtomicBoolean firstResourceCreated = new AtomicBoolean();
+
+		final SimpleDequePool<AtomicInteger> pool = PoolBuilder
+				.from(Mono.defer(() -> {
+					if (firstResourceCreated.getAndSet(true)) {
```
Comment (bsideup) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:48]: nit: could be `Mono.fromCallable(() -> firstResourceCreated.getAndSet(true) ? 200 : 1)`

File: src/test/java/reactor/pool/CommonPoolTest.java [hunk 6]
```diff
@@ -2365,4 +2366,82 @@ void raceShutdownAndPreAcquiredReleaseWithEviction(Function<PoolBuilder<AtomicIn
...
+
+		AbstractPool<Integer> pool = configAdjuster.apply(configBuilder);
+
+		assertThat(pool.warmup().block(Duration.ofSeconds(1))).as("warmup").isOne();
+
+		//there is one idle resource
+		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
+				.as("acquire on idle")
+				.isNotNull()
+				.hasFieldOrPropertyWithValue("poolable", 1);
```
Comment (bsideup) [inline src/test/java/reactor/pool/CommonPoolTest.java:2386]: this makes the tests harder to support because refactoring the method/field may not get reflected in tests. Consider using `.returns(1, it -> it.getPoolable())`

File: src/test/java/reactor/pool/CommonPoolTest.java [hunk 7]
```diff
@@ -2365,4 +2366,82 @@ void raceShutdownAndPreAcquiredReleaseWithEviction(Function<PoolBuilder<AtomicIn
...
+
+		//there is now idle resource, but still capacity
+		assertThat(pool.acquire().block(Duration.ofSeconds(1)))
+				.as("acquire on allocate")
+				.isNotNull()
+				.hasFieldOrPropertyWithValue("poolable", 2);
+
+		//there is now idle resource, no capacity, but pending 1 is allowed
+		//in order to test the scenario where we've reached maxPending, this pending must not be cancelled
+		final CountDownLatch latch = new CountDownLatch(1);
```
Comment (bsideup) [inline src/test/java/reactor/pool/CommonPoolTest.java:2429]: nit: alternatively, can be `pool.acquire().timeout(Duration.ofSeconds(1)).toFuture()`, to avoid `latch` + `endingSignal`

**Review by bsideup — APPROVED** [review]
Approving with a few nits in tests

File: src/test/java/reactor/pool/CommonPoolTest.java (hunk 6 above)
Comment (simonbasle) [reply src/test/java/reactor/pool/CommonPoolTest.java:2386]: didn't know about `returns`, neat!

Comment (bsideup) [reply src/test/java/reactor/pool/CommonPoolTest.java:2386]: the only downside is that it is "nameless" as compared to `hasFieldOrPropertyWithValue`, but the type safety and a method reference is IMO still better :)

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+
+public class SimpleDequePoolStressTest {
+
+	@JCStressTest
+	@Outcome(id = {"ACQUIRED '200', 0"}, expect = ACCEPTABLE,  desc = "acquired")
+	@Outcome(id = {"NOT ACQUIRED, 1"}, expect = ACCEPTABLE,  desc = "acquired failed fast during/before destroy")
+	@Outcome(id = {"ACQUIRED '1', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
+	@Outcome(id = {"ACQUIRED '1234', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
+	@State
+	public static class MaxPendingAcquireWhileDestroying {
```
Comment (shipilev) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:42]: What is the point of having this as nested class? (I am actually surprised jcstress even handles this case).

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+		@Actor
+		public void invalidate() {
+			ref.invalidate().block(Duration.ofMillis(100));
+		}
+
+		@Actor
+		public void acquisition(LI_Result r) {
+			try {
+				AtomicInteger ai = pool.acquire().block().poolable();
+				r.r1 = "ACQUIRED '" + ai.get() + "'";
```
Comment (shipilev) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:69]: jcstress tests are usually very sensitive to code that actors run. It is unconventional to use `String` results here. At very least, that slows down the tests, which makes less samples per time unit, and thus lowers the probability to catch the errors. I'd suggest taking `r1 = ai.get()`, and then doing `r1 = -1` on the exceptional path.

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+import static org.openjdk.jcstress.annotations.Expect.ACCEPTABLE;
+import static org.openjdk.jcstress.annotations.Expect.FORBIDDEN;
+
+public class SimpleDequePoolStressTest {
+
+	@JCStressTest
+	@Outcome(id = {"ACQUIRED '200', 0"}, expect = ACCEPTABLE,  desc = "acquired")
+	@Outcome(id = {"NOT ACQUIRED, 1"}, expect = ACCEPTABLE,  desc = "acquired failed fast during/before destroy")
+	@Outcome(id = {"ACQUIRED '1', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
+	@Outcome(id = {"ACQUIRED '1234', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
```
Comment (shipilev) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:40]: No need for curly braces in `id`. Also see the comment about using Strings as results.

**Review by shipilev — COMMENTED** [review]
Drive-by comment on `jcstress` usages.

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 8 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:42]: picked that up from @bsideup previous usage in reactor-core. I thought this was the go-to way to group up stress tests that pertain to the same class into a single file. (a second PR is going to add another stress test to the file)

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 9 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:69]: makes sense, yeah. the forbidden/acceptable results look better but if that is at the expense of the reliability of the test that's not a great tradeoff. that's what `desc` is about after all. will look into changing to `II_Result`.

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 8 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:42]: great, thanks for the confirmation

Comment (bsideup) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:42]: @shipilev simply to group.

Best Regards,
Your stress test for JCstress

😂

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java [hunk 11]
```diff
@@ -34,10 +34,10 @@
...
 
 	@JCStressTest
-	@Outcome(id = {"ACQUIRED '200', 0"}, expect = ACCEPTABLE,  desc = "acquired")
-	@Outcome(id = {"NOT ACQUIRED, 1"}, expect = ACCEPTABLE,  desc = "acquired failed fast during/before destroy")
-	@Outcome(id = {"ACQUIRED '1', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
-	@Outcome(id = {"ACQUIRED '1234', 0"}, expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
+	@Outcome(id = "200, 0", expect = ACCEPTABLE,  desc = "acquired a new resource")
+	@Outcome(id = "404, 1", expect = ACCEPTABLE,  desc = "acquired failed fast during/before destroy")
+	@Outcome(id = "1, 0", expect = FORBIDDEN,  desc = "acquired the first resource, before destroy")
+	@Outcome(id = "1234, 0", expect = FORBIDDEN,  desc = "acquired the first resource, after destroy")
```
Comment (shipilev) [inline src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:40]: I have a personal distaste for magic numbers here, and prefer to use round/special numbers where I can, for example: 1, 100, 200 for good cases here, and -1 for bad case. But then again, that's a personal preference.

**Review by shipilev — APPROVED** [review]
Acked `jcstress` fixes.

**Comment by bsideup** [comment]
@shipilev thank you for having a look! 👍

File: src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java (hunk 11 above)
Comment (simonbasle) [reply src/jcstress/java/reactor/pool/SimpleDequePoolStressTest.java:40]: that is a fair point, will try to strike a balance with the magic numbers so that they're kept simple while having state changes reflected as large gaps (so that there's no ambiguity in which state change led to the final value)
