### PR TITLE
Fix time unit mixup in `InstrumentedPool.PoolMetrics#isInactiveForMoreThan` default implementation

### LINKED ISSUE #176: InstrumentedPool.PoolMetrics isInactiveForMoreThan mixes time units
The `default boolean InstrumentedPool.PoolMetrics.isInactiveForMoreThan(Duration duration);` implementation compares the _seconds_ since the last interaction with the _milliseconds_ of the provided duration.

## Expected Behavior
I would expect the method to return `true` iff the last interaction was longer ago than the provided `duration`.

## Actual Behavior
The method returns `true` iff the last interaction is longer ago than the provided `duration * 1000`, basically.

## Steps to Reproduce

```java
@Test
void reproCase() {

        long inactiveSeconds = 5;
        var metrics = new InstrumentedPool.PoolMetrics() {

            @Override
            public int acquiredSize() {
                return 0;
            }

            @Override
            public int allocatedSize() {
                return 0;
            }

            @Override
            public int idleSize() {
                return 0;
            }

            @Override
            public int pendingAcquireSize() {
                return 0;
            }

            @Override
            public long secondsSinceLastInteraction() {
                return inactiveSeconds;
            }

            @Override
            public int getMaxAllocatedSize() {
                return 0;
            }

            @Override
            public int getMaxPendingAcquireSize() {
                return 0;
            }
        };
        
        assertTrue(metrics.isInactiveForMoreThan(Duration.ofSeconds(1)));
}
```

## Possible Solution

Change `this.secondsSinceLastInteraction() >= duration.toMillis()` to `this.secondsSinceLastInteraction() >= Math.ceil((double) duration.toMillis() / 1000)`.

## Your Environment

* Reactor version(s) used: `main` branch
* Other relevant libraries versions (eg. `netty`, ...): ---
* JVM version (`java -version`): ---
* OS and version (eg `uname -a`): ---

### PR DESCRIPTION
**Pull request by freelon**
Previously the units were mixed up and milliseconds were directly compared to seconds.

Fixes #176.

### CODE REVIEW

**Review by violetagg — APPROVED** [review]

**Comment by violetagg** [comment]
@reactor/team PTAL

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+
+class InstrumentedPoolPoolMetricsTest {
+
+	@Test
+	void testIsInactiveForMoreThan() {
+		InstrumentedPool.PoolMetrics metrics = new TestPool(2);
+
+		assertThat(metrics.isInactiveForMoreThan(Duration.ofMillis(1999))).isTrue();
+		assertThat(metrics.isInactiveForMoreThan(Duration.ofSeconds(2))).isTrue();
```
Comment (chemicL) [inline reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:32]: technically, 2s is not more than 2s, so I'd say this assertion should be false

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+		
+		assertThat(metrics.isInactiveForMoreThan(Duration.ofMillis(2001))).isFalse();
```
Comment (chemicL) [inline reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:34]: I think testing against 1999 millis would be useful :)

File: reactor-pool/src/main/java/reactor/pool/InstrumentedPool.java [hunk 3]
```diff
@@ -113,7 +113,7 @@ default long secondsSinceLastInteraction() {
 		 */
 		default boolean isInactiveForMoreThan(Duration duration) {
 			return acquiredSize() == 0 && idleSize() == 0 && pendingAcquireSize() == 0 && allocatedSize() == 0
-					&& secondsSinceLastInteraction() >= duration.toMillis();
+					&& !Duration.ofSeconds(secondsSinceLastInteraction()).minus(duration).isNegative();
```
Comment (chemicL) [inline reactor-pool/src/main/java/reactor/pool/InstrumentedPool.java:116]: Negation of negation is a bit difficult to follow, how about this?

    && duration.minusSeconds(secondsSinceLastInteraction()).isNegative()

**Review by chemicL — CHANGES_REQUESTED** [review]
Left a few comments, pretty quick to address. Thanks for the contribution!

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java (hunk 2 above)
Comment (violetagg) [reply reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:34]: isn't it tested on row 31?

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java (hunk 1 above)
Comment (violetagg) [reply reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:32]: wasn't this implemented according javadoc?

```
		/**
		 * A convenience way to check the pool is inactive, in the sense that {@link #acquiredSize()},
		 * {@link #idleSize()}, {@link #pendingAcquireSize()} and {@link #allocatedSize()} are all at zero
		 * and that the last recorded interaction with the pool ({@link #secondsSinceLastInteraction()})
		 * was more than or exactly {@code duration} ago.
		 *
		 * @return true if the pool can be considered inactive (see above), false otherwise
		 * @see #secondsSinceLastInteraction()
		 */
```

```
that the last recorded interaction with the pool ({@link #secondsSinceLastInteraction()})
		 * was more than or exactly {@code duration} ago.
```

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java (hunk 2 above)
Comment (chemicL) [reply reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:34]: My bad! 👓 Thanks for pointing it out :)

File: reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java (hunk 1 above)
Comment (chemicL) [reply reactor-pool/src/test/java/reactor/pool/InstrumentedPoolPoolMetricsTest.java:32]: You're right. Then it's not the implementation that is at fault, but the javadoc contradicts what the words in the method name say :(
`isInactiveForMoreThan` contradicts `more than or exactly `. In this case I have no more comments. If you're ok with this @violetagg please disregard my comment.

File: reactor-pool/src/main/java/reactor/pool/InstrumentedPool.java (hunk 3 above)
Comment (chemicL) [reply reactor-pool/src/main/java/reactor/pool/InstrumentedPool.java:116]: After tracing the history with @violetagg it seems this implementation is compliant with the javadoc and the other implementation, so it makes sense to keep it consistent. Please disregard my comment.

**Review by chemicL — APPROVED** [review]
After clarifications my comments are now resolved.

**Comment by violetagg** [comment]
@freelon Thanks for the PR
@chemicL Thanks for the review

This is merged into `0.2.x` for version `0.2.12` and into `main` for version `1.0.3`
